# Generated by Django 4.1.3 on 2022-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("alimentacao", "Alimentação"),
                    ("saude", "Saúde"),
                    ("moradia", "Moradia"),
                    ("transporte", "Transporte"),
                    ("educacao", "Educação"),
                    ("lazer", "Lazer"),
                    ("imprevisto", "Imprevistos"),
                    ("outras", "Outras"),
                ],
                default="outras",
                max_length=15,
            ),
        ),
    ]
